from __future__ import annotations

from .alignment import AlignmentTag, LegacyAlignmentTag
from .base import ParensTag, RawTag, SimpleTag, Tag
from .color import (
    AlphaTag,
    OutlineAlphaTag,
    OutlineColorTag,
    PrimaryAlphaTag,
    PrimaryColorTag,
    SecondaryAlphaTag,
    SecondaryColorTag,
    ShadowAlphaTag,
    ShadowColorTag,
)
from .font import (
    FontEncodingTag,
    FontNameTag,
    FontSizeAbsoluteTag,
    FontSizeRelativeTag,
    FontSizeTag,
    LetterSpacingTag,
)
from .geometry import (
    DrawingBaselineOffsetTag,
    DrawingModeTag,
    RotateXTag,
    RotateYTag,
    RotateZTag,
    ScaleTag,
    ScaleXTag,
    ScaleYTag,
    ShearXTag,
    ShearYTag,
)
from .karaoke import (
    KaraokeOutlineTag,
    KaraokeSweepTag,
    KaraokeTag,
    KaraokeTimeTag,
)
from .parens import (
    ClipRectTag,
    ClipShapeTag,
    ClipTag,
    FadeComplexTag,
    FadeSimpleTag,
    FadeTag,
    InverseClipRectTag,
    InverseClipShapeTag,
    InverseClipTag,
    MoveTag,
    OriginTag,
    PositionTag,
)
from .style import (
    BlurEdgeTag,
    BlurTag,
    BoldSimpleTag,
    BoldTag,
    BoldWeightTag,
    BorderTag,
    BorderXTag,
    BorderYTag,
    ItalicTag,
    ResetStyleTag,
    ShadowTag,
    ShadowXTag,
    ShadowYTag,
    StrikeoutTag,
    UnderlineTag,
    WrapStyleTag,
)
from .transform import TransformTag

__all__ = [
    "AlignmentTag",
    "AlphaTag",
    "BlurEdgeTag",
    "BlurTag",
    "BoldSimpleTag",
    "BoldTag",
    "BoldWeightTag",
    "BorderTag",
    "BorderXTag",
    "BorderYTag",
    "ClipRectTag",
    "ClipShapeTag",
    "ClipTag",
    "DrawingBaselineOffsetTag",
    "DrawingModeTag",
    "FadeComplexTag",
    "FadeSimpleTag",
    "FadeTag",
    "FontEncodingTag",
    "FontNameTag",
    "FontSizeAbsoluteTag",
    "FontSizeRelativeTag",
    "FontSizeTag",
    "InverseClipRectTag",
    "InverseClipShapeTag",
    "InverseClipTag",
    "ItalicTag",
    "KaraokeOutlineTag",
    "KaraokeSweepTag",
    "KaraokeTag",
    "KaraokeTimeTag",
    "LegacyAlignmentTag",
    "LetterSpacingTag",
    "MoveTag",
    "OriginTag",
    "OutlineAlphaTag",
    "OutlineColorTag",
    "ParensTag",
    "PositionTag",
    "PrimaryAlphaTag",
    "PrimaryColorTag",
    "RawTag",
    "ResetStyleTag",
    "RotateXTag",
    "RotateYTag",
    "RotateZTag",
    "STANDARD_TAG_SET",
    "ScaleTag",
    "ScaleXTag",
    "ScaleYTag",
    "SecondaryAlphaTag",
    "SecondaryColorTag",
    "ShadowAlphaTag",
    "ShadowColorTag",
    "ShadowTag",
    "ShadowXTag",
    "ShadowYTag",
    "ShearXTag",
    "ShearYTag",
    "SimpleTag",
    "StrikeoutTag",
    "Tag",
    "TransformTag",
    "UnderlineTag",
    "WrapStyleTag",
]

STANDARD_TAG_SET: frozenset[type[Tag]] = frozenset(
    {
        # Simple Tags
        AlphaTag,
        AlignmentTag,
        BlurEdgeTag,
        BlurTag,
        BoldTag,
        BorderTag,
        BorderXTag,
        BorderYTag,
        DrawingBaselineOffsetTag,
        DrawingModeTag,
        FontEncodingTag,
        FontNameTag,
        FontSizeTag,
        ItalicTag,
        KaraokeOutlineTag,
        KaraokeSweepTag,
        KaraokeTag,
        KaraokeTimeTag,
        LegacyAlignmentTag,
        LetterSpacingTag,
        OutlineAlphaTag,
        OutlineColorTag,
        PrimaryAlphaTag,
        PrimaryColorTag,
        ResetStyleTag,
        RotateXTag,
        RotateYTag,
        RotateZTag,
        ScaleTag,
        ScaleXTag,
        ScaleYTag,
        SecondaryAlphaTag,
        SecondaryColorTag,
        ShadowAlphaTag,
        ShadowColorTag,
        ShadowTag,
        ShadowXTag,
        ShadowYTag,
        ShearXTag,
        ShearYTag,
        StrikeoutTag,
        UnderlineTag,
        WrapStyleTag,
        # Parenthesised Tags
        ClipTag,  # type: ignore[type-abstract]
        FadeTag,  # type: ignore[type-abstract]
        InverseClipTag,  # type: ignore[type-abstract]
        MoveTag,
        OriginTag,
        PositionTag,
        # TransformTag
        TransformTag,
    }
)
